(define (problem drone_problem_d1_r0_l100_p100_c100_g100_ct2)
(:domain ubermedics)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	loc36 - location
	loc37 - location
	loc38 - location
	loc39 - location
	loc40 - location
	loc41 - location
	loc42 - location
	loc43 - location
	loc44 - location
	loc45 - location
	loc46 - location
	loc47 - location
	loc48 - location
	loc49 - location
	loc50 - location
	loc51 - location
	loc52 - location
	loc53 - location
	loc54 - location
	loc55 - location
	loc56 - location
	loc57 - location
	loc58 - location
	loc59 - location
	loc60 - location
	loc61 - location
	loc62 - location
	loc63 - location
	loc64 - location
	loc65 - location
	loc66 - location
	loc67 - location
	loc68 - location
	loc69 - location
	loc70 - location
	loc71 - location
	loc72 - location
	loc73 - location
	loc74 - location
	loc75 - location
	loc76 - location
	loc77 - location
	loc78 - location
	loc79 - location
	loc80 - location
	loc81 - location
	loc82 - location
	loc83 - location
	loc84 - location
	loc85 - location
	loc86 - location
	loc87 - location
	loc88 - location
	loc89 - location
	loc90 - location
	loc91 - location
	loc92 - location
	loc93 - location
	loc94 - location
	loc95 - location
	loc96 - location
	loc97 - location
	loc98 - location
	loc99 - location
	loc100 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	crate43 - crate
	crate44 - crate
	crate45 - crate
	crate46 - crate
	crate47 - crate
	crate48 - crate
	crate49 - crate
	crate50 - crate
	crate51 - crate
	crate52 - crate
	crate53 - crate
	crate54 - crate
	crate55 - crate
	crate56 - crate
	crate57 - crate
	crate58 - crate
	crate59 - crate
	crate60 - crate
	crate61 - crate
	crate62 - crate
	crate63 - crate
	crate64 - crate
	crate65 - crate
	crate66 - crate
	crate67 - crate
	crate68 - crate
	crate69 - crate
	crate70 - crate
	crate71 - crate
	crate72 - crate
	crate73 - crate
	crate74 - crate
	crate75 - crate
	crate76 - crate
	crate77 - crate
	crate78 - crate
	crate79 - crate
	crate80 - crate
	crate81 - crate
	crate82 - crate
	crate83 - crate
	crate84 - crate
	crate85 - crate
	crate86 - crate
	crate87 - crate
	crate88 - crate
	crate89 - crate
	crate90 - crate
	crate91 - crate
	crate92 - crate
	crate93 - crate
	crate94 - crate
	crate95 - crate
	crate96 - crate
	crate97 - crate
	crate98 - crate
	crate99 - crate
	crate100 - crate
	food - contents
	medicine - contents
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	person34 - person
	person35 - person
	person36 - person
	person37 - person
	person38 - person
	person39 - person
	person40 - person
	person41 - person
	person42 - person
	person43 - person
	person44 - person
	person45 - person
	person46 - person
	person47 - person
	person48 - person
	person49 - person
	person50 - person
	person51 - person
	person52 - person
	person53 - person
	person54 - person
	person55 - person
	person56 - person
	person57 - person
	person58 - person
	person59 - person
	person60 - person
	person61 - person
	person62 - person
	person63 - person
	person64 - person
	person65 - person
	person66 - person
	person67 - person
	person68 - person
	person69 - person
	person70 - person
	person71 - person
	person72 - person
	person73 - person
	person74 - person
	person75 - person
	person76 - person
	person77 - person
	person78 - person
	person79 - person
	person80 - person
	person81 - person
	person82 - person
	person83 - person
	person84 - person
	person85 - person
	person86 - person
	person87 - person
	person88 - person
	person89 - person
	person90 - person
	person91 - person
	person92 - person
	person93 - person
	person94 - person
	person95 - person
	person96 - person
	person97 - person
	person98 - person
	person99 - person
	person100 - person
)
(:init
	(drone-at drone1 depot)
	(arm-free-left drone1)
	(arm-free-right drone1)
	(crate-at crate1 depot)
	(crate-at crate2 depot)
	(crate-at crate3 depot)
	(crate-at crate4 depot)
	(crate-at crate5 depot)
	(crate-at crate6 depot)
	(crate-at crate7 depot)
	(crate-at crate8 depot)
	(crate-at crate9 depot)
	(crate-at crate10 depot)
	(crate-at crate11 depot)
	(crate-at crate12 depot)
	(crate-at crate13 depot)
	(crate-at crate14 depot)
	(crate-at crate15 depot)
	(crate-at crate16 depot)
	(crate-at crate17 depot)
	(crate-at crate18 depot)
	(crate-at crate19 depot)
	(crate-at crate20 depot)
	(crate-at crate21 depot)
	(crate-at crate22 depot)
	(crate-at crate23 depot)
	(crate-at crate24 depot)
	(crate-at crate25 depot)
	(crate-at crate26 depot)
	(crate-at crate27 depot)
	(crate-at crate28 depot)
	(crate-at crate29 depot)
	(crate-at crate30 depot)
	(crate-at crate31 depot)
	(crate-at crate32 depot)
	(crate-at crate33 depot)
	(crate-at crate34 depot)
	(crate-at crate35 depot)
	(crate-at crate36 depot)
	(crate-at crate37 depot)
	(crate-at crate38 depot)
	(crate-at crate39 depot)
	(crate-at crate40 depot)
	(crate-at crate41 depot)
	(crate-at crate42 depot)
	(crate-at crate43 depot)
	(crate-at crate44 depot)
	(crate-at crate45 depot)
	(crate-at crate46 depot)
	(crate-at crate47 depot)
	(crate-at crate48 depot)
	(crate-at crate49 depot)
	(crate-at crate50 depot)
	(crate-at crate51 depot)
	(crate-at crate52 depot)
	(crate-at crate53 depot)
	(crate-at crate54 depot)
	(crate-at crate55 depot)
	(crate-at crate56 depot)
	(crate-at crate57 depot)
	(crate-at crate58 depot)
	(crate-at crate59 depot)
	(crate-at crate60 depot)
	(crate-at crate61 depot)
	(crate-at crate62 depot)
	(crate-at crate63 depot)
	(crate-at crate64 depot)
	(crate-at crate65 depot)
	(crate-at crate66 depot)
	(crate-at crate67 depot)
	(crate-at crate68 depot)
	(crate-at crate69 depot)
	(crate-at crate70 depot)
	(crate-at crate71 depot)
	(crate-at crate72 depot)
	(crate-at crate73 depot)
	(crate-at crate74 depot)
	(crate-at crate75 depot)
	(crate-at crate76 depot)
	(crate-at crate77 depot)
	(crate-at crate78 depot)
	(crate-at crate79 depot)
	(crate-at crate80 depot)
	(crate-at crate81 depot)
	(crate-at crate82 depot)
	(crate-at crate83 depot)
	(crate-at crate84 depot)
	(crate-at crate85 depot)
	(crate-at crate86 depot)
	(crate-at crate87 depot)
	(crate-at crate88 depot)
	(crate-at crate89 depot)
	(crate-at crate90 depot)
	(crate-at crate91 depot)
	(crate-at crate92 depot)
	(crate-at crate93 depot)
	(crate-at crate94 depot)
	(crate-at crate95 depot)
	(crate-at crate96 depot)
	(crate-at crate97 depot)
	(crate-at crate98 depot)
	(crate-at crate99 depot)
	(crate-at crate100 depot)
	(crate-has crate1 food)
	(crate-has crate2 food)
	(crate-has crate3 food)
	(crate-has crate4 food)
	(crate-has crate5 food)
	(crate-has crate6 food)
	(crate-has crate7 food)
	(crate-has crate8 food)
	(crate-has crate9 food)
	(crate-has crate10 food)
	(crate-has crate11 food)
	(crate-has crate12 food)
	(crate-has crate13 food)
	(crate-has crate14 food)
	(crate-has crate15 food)
	(crate-has crate16 food)
	(crate-has crate17 food)
	(crate-has crate18 food)
	(crate-has crate19 food)
	(crate-has crate20 food)
	(crate-has crate21 food)
	(crate-has crate22 food)
	(crate-has crate23 food)
	(crate-has crate24 food)
	(crate-has crate25 food)
	(crate-has crate26 food)
	(crate-has crate27 food)
	(crate-has crate28 food)
	(crate-has crate29 food)
	(crate-has crate30 food)
	(crate-has crate31 food)
	(crate-has crate32 food)
	(crate-has crate33 food)
	(crate-has crate34 food)
	(crate-has crate35 food)
	(crate-has crate36 food)
	(crate-has crate37 food)
	(crate-has crate38 food)
	(crate-has crate39 food)
	(crate-has crate40 food)
	(crate-has crate41 food)
	(crate-has crate42 food)
	(crate-has crate43 food)
	(crate-has crate44 food)
	(crate-has crate45 food)
	(crate-has crate46 food)
	(crate-has crate47 food)
	(crate-has crate48 food)
	(crate-has crate49 food)
	(crate-has crate50 food)
	(crate-has crate51 food)
	(crate-has crate52 food)
	(crate-has crate53 food)
	(crate-has crate54 food)
	(crate-has crate55 food)
	(crate-has crate56 food)
	(crate-has crate57 food)
	(crate-has crate58 food)
	(crate-has crate59 food)
	(crate-has crate60 food)
	(crate-has crate61 food)
	(crate-has crate62 food)
	(crate-has crate63 food)
	(crate-has crate64 food)
	(crate-has crate65 food)
	(crate-has crate66 food)
	(crate-has crate67 food)
	(crate-has crate68 food)
	(crate-has crate69 food)
	(crate-has crate70 food)
	(crate-has crate71 food)
	(crate-has crate72 food)
	(crate-has crate73 food)
	(crate-has crate74 food)
	(crate-has crate75 food)
	(crate-has crate76 food)
	(crate-has crate77 food)
	(crate-has crate78 food)
	(crate-has crate79 food)
	(crate-has crate80 food)
	(crate-has crate81 food)
	(crate-has crate82 food)
	(crate-has crate83 medicine)
	(crate-has crate84 medicine)
	(crate-has crate85 medicine)
	(crate-has crate86 medicine)
	(crate-has crate87 medicine)
	(crate-has crate88 medicine)
	(crate-has crate89 medicine)
	(crate-has crate90 medicine)
	(crate-has crate91 medicine)
	(crate-has crate92 medicine)
	(crate-has crate93 medicine)
	(crate-has crate94 medicine)
	(crate-has crate95 medicine)
	(crate-has crate96 medicine)
	(crate-has crate97 medicine)
	(crate-has crate98 medicine)
	(crate-has crate99 medicine)
	(crate-has crate100 medicine)
	(person-at person1 loc46)
	(person-at person2 loc45)
	(person-at person3 loc15)
	(person-at person4 loc68)
	(person-at person5 loc86)
	(person-at person6 loc11)
	(person-at person7 loc19)
	(person-at person8 loc87)
	(person-at person9 loc9)
	(person-at person10 loc55)
	(person-at person11 loc81)
	(person-at person12 loc49)
	(person-at person13 loc89)
	(person-at person14 loc18)
	(person-at person15 loc9)
	(person-at person16 loc56)
	(person-at person17 loc64)
	(person-at person18 loc29)
	(person-at person19 loc7)
	(person-at person20 loc8)
	(person-at person21 loc95)
	(person-at person22 loc40)
	(person-at person23 loc82)
	(person-at person24 loc14)
	(person-at person25 loc84)
	(person-at person26 loc34)
	(person-at person27 loc20)
	(person-at person28 loc16)
	(person-at person29 loc8)
	(person-at person30 loc84)
	(person-at person31 loc31)
	(person-at person32 loc32)
	(person-at person33 loc19)
	(person-at person34 loc11)
	(person-at person35 loc26)
	(person-at person36 loc49)
	(person-at person37 loc87)
	(person-at person38 loc45)
	(person-at person39 loc73)
	(person-at person40 loc40)
	(person-at person41 loc87)
	(person-at person42 loc13)
	(person-at person43 loc90)
	(person-at person44 loc56)
	(person-at person45 loc66)
	(person-at person46 loc7)
	(person-at person47 loc46)
	(person-at person48 loc14)
	(person-at person49 loc93)
	(person-at person50 loc70)
	(person-at person51 loc51)
	(person-at person52 loc91)
	(person-at person53 loc27)
	(person-at person54 loc43)
	(person-at person55 loc77)
	(person-at person56 loc41)
	(person-at person57 loc41)
	(person-at person58 loc33)
	(person-at person59 loc9)
	(person-at person60 loc73)
	(person-at person61 loc19)
	(person-at person62 loc27)
	(person-at person63 loc57)
	(person-at person64 loc21)
	(person-at person65 loc43)
	(person-at person66 loc90)
	(person-at person67 loc64)
	(person-at person68 loc31)
	(person-at person69 loc46)
	(person-at person70 loc15)
	(person-at person71 loc7)
	(person-at person72 loc72)
	(person-at person73 loc94)
	(person-at person74 loc38)
	(person-at person75 loc77)
	(person-at person76 loc72)
	(person-at person77 loc47)
	(person-at person78 loc25)
	(person-at person79 loc32)
	(person-at person80 loc1)
	(person-at person81 loc15)
	(person-at person82 loc72)
	(person-at person83 loc2)
	(person-at person84 loc80)
	(person-at person85 loc15)
	(person-at person86 loc41)
	(person-at person87 loc21)
	(person-at person88 loc52)
	(person-at person89 loc98)
	(person-at person90 loc34)
	(person-at person91 loc21)
	(person-at person92 loc2)
	(person-at person93 loc72)
	(person-at person94 loc94)
	(person-at person95 loc36)
	(person-at person96 loc93)
	(person-at person97 loc65)
	(person-at person98 loc55)
	(person-at person99 loc96)
	(person-at person100 loc81)
)
(:goal (and

	(drone-at drone1 depot)	(person-has person1 medicine)
	(person-has person2 medicine)
	(person-has person3 food)
	(person-has person4 food)
	(person-has person4 medicine)
	(person-has person5 food)
	(person-has person6 food)
	(person-has person7 food)
	(person-has person8 food)
	(person-has person10 food)
	(person-has person11 food)
	(person-has person11 medicine)
	(person-has person13 food)
	(person-has person14 food)
	(person-has person14 medicine)
	(person-has person15 food)
	(person-has person16 food)
	(person-has person16 medicine)
	(person-has person18 food)
	(person-has person19 food)
	(person-has person20 food)
	(person-has person21 food)
	(person-has person22 food)
	(person-has person23 food)
	(person-has person24 food)
	(person-has person25 food)
	(person-has person26 food)
	(person-has person27 medicine)
	(person-has person28 food)
	(person-has person28 medicine)
	(person-has person29 food)
	(person-has person31 food)
	(person-has person32 food)
	(person-has person34 food)
	(person-has person35 food)
	(person-has person36 food)
	(person-has person37 food)
	(person-has person38 food)
	(person-has person39 food)
	(person-has person39 medicine)
	(person-has person40 food)
	(person-has person41 food)
	(person-has person42 food)
	(person-has person42 medicine)
	(person-has person43 food)
	(person-has person44 food)
	(person-has person46 food)
	(person-has person48 food)
	(person-has person50 food)
	(person-has person51 food)
	(person-has person53 food)
	(person-has person54 food)
	(person-has person55 food)
	(person-has person56 food)
	(person-has person58 food)
	(person-has person58 medicine)
	(person-has person59 food)
	(person-has person60 food)
	(person-has person61 food)
	(person-has person62 food)
	(person-has person63 food)
	(person-has person64 food)
	(person-has person65 food)
	(person-has person66 food)
	(person-has person67 food)
	(person-has person68 food)
	(person-has person69 food)
	(person-has person69 medicine)
	(person-has person70 food)
	(person-has person71 food)
	(person-has person72 food)
	(person-has person73 food)
	(person-has person74 food)
	(person-has person75 food)
	(person-has person76 food)
	(person-has person77 food)
	(person-has person78 food)
	(person-has person79 medicine)
	(person-has person80 food)
	(person-has person81 food)
	(person-has person83 food)
	(person-has person83 medicine)
	(person-has person84 food)
	(person-has person85 food)
	(person-has person85 medicine)
	(person-has person86 food)
	(person-has person87 food)
	(person-has person88 food)
	(person-has person89 food)
	(person-has person90 food)
	(person-has person91 food)
	(person-has person92 food)
	(person-has person95 food)
	(person-has person95 medicine)
	(person-has person96 food)
	(person-has person96 medicine)
	(person-has person97 food)
	(person-has person97 medicine)
	(person-has person98 food)
	(person-has person100 food)
	))
)
