(define (problem drone_problem_d1_r0_l30_p30_c30_g30_ct2)
(:domain ubermedics)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	food - contents
	medicine - contents
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
)
(:init
	(drone-at drone1 depot)
	(arm-free-left drone1)
	(arm-free-right drone1)
	(crate-at crate1 depot)
	(crate-at crate2 depot)
	(crate-at crate3 depot)
	(crate-at crate4 depot)
	(crate-at crate5 depot)
	(crate-at crate6 depot)
	(crate-at crate7 depot)
	(crate-at crate8 depot)
	(crate-at crate9 depot)
	(crate-at crate10 depot)
	(crate-at crate11 depot)
	(crate-at crate12 depot)
	(crate-at crate13 depot)
	(crate-at crate14 depot)
	(crate-at crate15 depot)
	(crate-at crate16 depot)
	(crate-at crate17 depot)
	(crate-at crate18 depot)
	(crate-at crate19 depot)
	(crate-at crate20 depot)
	(crate-at crate21 depot)
	(crate-at crate22 depot)
	(crate-at crate23 depot)
	(crate-at crate24 depot)
	(crate-at crate25 depot)
	(crate-at crate26 depot)
	(crate-at crate27 depot)
	(crate-at crate28 depot)
	(crate-at crate29 depot)
	(crate-at crate30 depot)
	(crate-has crate1 food)
	(crate-has crate2 food)
	(crate-has crate3 food)
	(crate-has crate4 food)
	(crate-has crate5 food)
	(crate-has crate6 food)
	(crate-has crate7 food)
	(crate-has crate8 food)
	(crate-has crate9 food)
	(crate-has crate10 food)
	(crate-has crate11 medicine)
	(crate-has crate12 medicine)
	(crate-has crate13 medicine)
	(crate-has crate14 medicine)
	(crate-has crate15 medicine)
	(crate-has crate16 medicine)
	(crate-has crate17 medicine)
	(crate-has crate18 medicine)
	(crate-has crate19 medicine)
	(crate-has crate20 medicine)
	(crate-has crate21 medicine)
	(crate-has crate22 medicine)
	(crate-has crate23 medicine)
	(crate-has crate24 medicine)
	(crate-has crate25 medicine)
	(crate-has crate26 medicine)
	(crate-has crate27 medicine)
	(crate-has crate28 medicine)
	(crate-has crate29 medicine)
	(crate-has crate30 medicine)
	(person-at person1 loc21)
	(person-at person2 loc9)
	(person-at person3 loc16)
	(person-at person4 loc15)
	(person-at person5 loc26)
	(person-at person6 loc25)
	(person-at person7 loc4)
	(person-at person8 loc24)
	(person-at person9 loc27)
	(person-at person10 loc23)
	(person-at person11 loc25)
	(person-at person12 loc16)
	(person-at person13 loc29)
	(person-at person14 loc7)
	(person-at person15 loc14)
	(person-at person16 loc10)
	(person-at person17 loc19)
	(person-at person18 loc19)
	(person-at person19 loc29)
	(person-at person20 loc2)
	(person-at person21 loc13)
	(person-at person22 loc25)
	(person-at person23 loc13)
	(person-at person24 loc21)
	(person-at person25 loc7)
	(person-at person26 loc26)
	(person-at person27 loc1)
	(person-at person28 loc11)
	(person-at person29 loc17)
	(person-at person30 loc1)
)
(:goal (and

	(drone-at drone1 depot)	(person-has person1 medicine)
	(person-has person2 medicine)
	(person-has person3 food)
	(person-has person3 medicine)
	(person-has person4 food)
	(person-has person4 medicine)
	(person-has person5 food)
	(person-has person5 medicine)
	(person-has person6 food)
	(person-has person6 medicine)
	(person-has person7 food)
	(person-has person7 medicine)
	(person-has person8 food)
	(person-has person10 medicine)
	(person-has person11 medicine)
	(person-has person12 medicine)
	(person-has person13 medicine)
	(person-has person14 food)
	(person-has person15 medicine)
	(person-has person16 medicine)
	(person-has person17 food)
	(person-has person17 medicine)
	(person-has person19 medicine)
	(person-has person20 medicine)
	(person-has person25 medicine)
	(person-has person26 medicine)
	(person-has person27 medicine)
	(person-has person28 food)
	(person-has person30 food)
	(person-has person30 medicine)
	))
)
