(define (problem drone_problem_d1_r0_l60_p60_c60_g60_ct2)
(:domain ubermedics)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	loc36 - location
	loc37 - location
	loc38 - location
	loc39 - location
	loc40 - location
	loc41 - location
	loc42 - location
	loc43 - location
	loc44 - location
	loc45 - location
	loc46 - location
	loc47 - location
	loc48 - location
	loc49 - location
	loc50 - location
	loc51 - location
	loc52 - location
	loc53 - location
	loc54 - location
	loc55 - location
	loc56 - location
	loc57 - location
	loc58 - location
	loc59 - location
	loc60 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	crate43 - crate
	crate44 - crate
	crate45 - crate
	crate46 - crate
	crate47 - crate
	crate48 - crate
	crate49 - crate
	crate50 - crate
	crate51 - crate
	crate52 - crate
	crate53 - crate
	crate54 - crate
	crate55 - crate
	crate56 - crate
	crate57 - crate
	crate58 - crate
	crate59 - crate
	crate60 - crate
	food - contents
	medicine - contents
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	person34 - person
	person35 - person
	person36 - person
	person37 - person
	person38 - person
	person39 - person
	person40 - person
	person41 - person
	person42 - person
	person43 - person
	person44 - person
	person45 - person
	person46 - person
	person47 - person
	person48 - person
	person49 - person
	person50 - person
	person51 - person
	person52 - person
	person53 - person
	person54 - person
	person55 - person
	person56 - person
	person57 - person
	person58 - person
	person59 - person
	person60 - person
)
(:init
	(drone-at drone1 depot)
	(arm-free-left drone1)
	(arm-free-right drone1)
	(crate-at crate1 depot)
	(crate-at crate2 depot)
	(crate-at crate3 depot)
	(crate-at crate4 depot)
	(crate-at crate5 depot)
	(crate-at crate6 depot)
	(crate-at crate7 depot)
	(crate-at crate8 depot)
	(crate-at crate9 depot)
	(crate-at crate10 depot)
	(crate-at crate11 depot)
	(crate-at crate12 depot)
	(crate-at crate13 depot)
	(crate-at crate14 depot)
	(crate-at crate15 depot)
	(crate-at crate16 depot)
	(crate-at crate17 depot)
	(crate-at crate18 depot)
	(crate-at crate19 depot)
	(crate-at crate20 depot)
	(crate-at crate21 depot)
	(crate-at crate22 depot)
	(crate-at crate23 depot)
	(crate-at crate24 depot)
	(crate-at crate25 depot)
	(crate-at crate26 depot)
	(crate-at crate27 depot)
	(crate-at crate28 depot)
	(crate-at crate29 depot)
	(crate-at crate30 depot)
	(crate-at crate31 depot)
	(crate-at crate32 depot)
	(crate-at crate33 depot)
	(crate-at crate34 depot)
	(crate-at crate35 depot)
	(crate-at crate36 depot)
	(crate-at crate37 depot)
	(crate-at crate38 depot)
	(crate-at crate39 depot)
	(crate-at crate40 depot)
	(crate-at crate41 depot)
	(crate-at crate42 depot)
	(crate-at crate43 depot)
	(crate-at crate44 depot)
	(crate-at crate45 depot)
	(crate-at crate46 depot)
	(crate-at crate47 depot)
	(crate-at crate48 depot)
	(crate-at crate49 depot)
	(crate-at crate50 depot)
	(crate-at crate51 depot)
	(crate-at crate52 depot)
	(crate-at crate53 depot)
	(crate-at crate54 depot)
	(crate-at crate55 depot)
	(crate-at crate56 depot)
	(crate-at crate57 depot)
	(crate-at crate58 depot)
	(crate-at crate59 depot)
	(crate-at crate60 depot)
	(crate-has crate1 food)
	(crate-has crate2 food)
	(crate-has crate3 food)
	(crate-has crate4 food)
	(crate-has crate5 food)
	(crate-has crate6 food)
	(crate-has crate7 food)
	(crate-has crate8 food)
	(crate-has crate9 food)
	(crate-has crate10 food)
	(crate-has crate11 food)
	(crate-has crate12 food)
	(crate-has crate13 food)
	(crate-has crate14 food)
	(crate-has crate15 food)
	(crate-has crate16 food)
	(crate-has crate17 food)
	(crate-has crate18 food)
	(crate-has crate19 food)
	(crate-has crate20 food)
	(crate-has crate21 food)
	(crate-has crate22 food)
	(crate-has crate23 food)
	(crate-has crate24 food)
	(crate-has crate25 food)
	(crate-has crate26 food)
	(crate-has crate27 food)
	(crate-has crate28 food)
	(crate-has crate29 food)
	(crate-has crate30 food)
	(crate-has crate31 food)
	(crate-has crate32 food)
	(crate-has crate33 food)
	(crate-has crate34 food)
	(crate-has crate35 food)
	(crate-has crate36 food)
	(crate-has crate37 food)
	(crate-has crate38 food)
	(crate-has crate39 food)
	(crate-has crate40 food)
	(crate-has crate41 food)
	(crate-has crate42 food)
	(crate-has crate43 food)
	(crate-has crate44 food)
	(crate-has crate45 food)
	(crate-has crate46 food)
	(crate-has crate47 food)
	(crate-has crate48 food)
	(crate-has crate49 food)
	(crate-has crate50 food)
	(crate-has crate51 food)
	(crate-has crate52 medicine)
	(crate-has crate53 medicine)
	(crate-has crate54 medicine)
	(crate-has crate55 medicine)
	(crate-has crate56 medicine)
	(crate-has crate57 medicine)
	(crate-has crate58 medicine)
	(crate-has crate59 medicine)
	(crate-has crate60 medicine)
	(person-at person1 loc38)
	(person-at person2 loc45)
	(person-at person3 loc3)
	(person-at person4 loc47)
	(person-at person5 loc31)
	(person-at person6 loc59)
	(person-at person7 loc5)
	(person-at person8 loc11)
	(person-at person9 loc34)
	(person-at person10 loc9)
	(person-at person11 loc9)
	(person-at person12 loc37)
	(person-at person13 loc25)
	(person-at person14 loc28)
	(person-at person15 loc57)
	(person-at person16 loc6)
	(person-at person17 loc3)
	(person-at person18 loc53)
	(person-at person19 loc28)
	(person-at person20 loc29)
	(person-at person21 loc9)
	(person-at person22 loc47)
	(person-at person23 loc50)
	(person-at person24 loc55)
	(person-at person25 loc22)
	(person-at person26 loc13)
	(person-at person27 loc57)
	(person-at person28 loc3)
	(person-at person29 loc6)
	(person-at person30 loc44)
	(person-at person31 loc36)
	(person-at person32 loc4)
	(person-at person33 loc21)
	(person-at person34 loc33)
	(person-at person35 loc34)
	(person-at person36 loc53)
	(person-at person37 loc53)
	(person-at person38 loc3)
	(person-at person39 loc53)
	(person-at person40 loc24)
	(person-at person41 loc35)
	(person-at person42 loc40)
	(person-at person43 loc47)
	(person-at person44 loc45)
	(person-at person45 loc29)
	(person-at person46 loc54)
	(person-at person47 loc56)
	(person-at person48 loc16)
	(person-at person49 loc26)
	(person-at person50 loc21)
	(person-at person51 loc32)
	(person-at person52 loc27)
	(person-at person53 loc13)
	(person-at person54 loc29)
	(person-at person55 loc38)
	(person-at person56 loc58)
	(person-at person57 loc57)
	(person-at person58 loc8)
	(person-at person59 loc49)
	(person-at person60 loc55)
)
(:goal (and

	(drone-at drone1 depot)	(person-has person1 food)
	(person-has person2 food)
	(person-has person3 food)
	(person-has person4 food)
	(person-has person6 medicine)
	(person-has person7 food)
	(person-has person8 food)
	(person-has person9 food)
	(person-has person10 food)
	(person-has person10 medicine)
	(person-has person11 food)
	(person-has person12 food)
	(person-has person13 food)
	(person-has person14 food)
	(person-has person14 medicine)
	(person-has person16 food)
	(person-has person17 food)
	(person-has person18 food)
	(person-has person19 food)
	(person-has person20 food)
	(person-has person21 food)
	(person-has person23 food)
	(person-has person24 food)
	(person-has person25 food)
	(person-has person25 medicine)
	(person-has person26 food)
	(person-has person27 food)
	(person-has person28 food)
	(person-has person29 food)
	(person-has person30 food)
	(person-has person30 medicine)
	(person-has person32 food)
	(person-has person33 food)
	(person-has person34 food)
	(person-has person36 food)
	(person-has person37 medicine)
	(person-has person38 food)
	(person-has person39 food)
	(person-has person40 food)
	(person-has person41 food)
	(person-has person42 food)
	(person-has person43 food)
	(person-has person43 medicine)
	(person-has person44 food)
	(person-has person45 food)
	(person-has person46 food)
	(person-has person47 food)
	(person-has person48 food)
	(person-has person48 medicine)
	(person-has person49 food)
	(person-has person50 food)
	(person-has person51 food)
	(person-has person52 food)
	(person-has person53 food)
	(person-has person56 food)
	(person-has person57 food)
	(person-has person58 food)
	(person-has person58 medicine)
	(person-has person59 food)
	(person-has person60 food)
	))
)
