(define (problem drone_problem_d1_r0_l80_p80_c80_g80_ct2)
(:domain ubermedics)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	loc36 - location
	loc37 - location
	loc38 - location
	loc39 - location
	loc40 - location
	loc41 - location
	loc42 - location
	loc43 - location
	loc44 - location
	loc45 - location
	loc46 - location
	loc47 - location
	loc48 - location
	loc49 - location
	loc50 - location
	loc51 - location
	loc52 - location
	loc53 - location
	loc54 - location
	loc55 - location
	loc56 - location
	loc57 - location
	loc58 - location
	loc59 - location
	loc60 - location
	loc61 - location
	loc62 - location
	loc63 - location
	loc64 - location
	loc65 - location
	loc66 - location
	loc67 - location
	loc68 - location
	loc69 - location
	loc70 - location
	loc71 - location
	loc72 - location
	loc73 - location
	loc74 - location
	loc75 - location
	loc76 - location
	loc77 - location
	loc78 - location
	loc79 - location
	loc80 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	crate43 - crate
	crate44 - crate
	crate45 - crate
	crate46 - crate
	crate47 - crate
	crate48 - crate
	crate49 - crate
	crate50 - crate
	crate51 - crate
	crate52 - crate
	crate53 - crate
	crate54 - crate
	crate55 - crate
	crate56 - crate
	crate57 - crate
	crate58 - crate
	crate59 - crate
	crate60 - crate
	crate61 - crate
	crate62 - crate
	crate63 - crate
	crate64 - crate
	crate65 - crate
	crate66 - crate
	crate67 - crate
	crate68 - crate
	crate69 - crate
	crate70 - crate
	crate71 - crate
	crate72 - crate
	crate73 - crate
	crate74 - crate
	crate75 - crate
	crate76 - crate
	crate77 - crate
	crate78 - crate
	crate79 - crate
	crate80 - crate
	food - contents
	medicine - contents
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	person34 - person
	person35 - person
	person36 - person
	person37 - person
	person38 - person
	person39 - person
	person40 - person
	person41 - person
	person42 - person
	person43 - person
	person44 - person
	person45 - person
	person46 - person
	person47 - person
	person48 - person
	person49 - person
	person50 - person
	person51 - person
	person52 - person
	person53 - person
	person54 - person
	person55 - person
	person56 - person
	person57 - person
	person58 - person
	person59 - person
	person60 - person
	person61 - person
	person62 - person
	person63 - person
	person64 - person
	person65 - person
	person66 - person
	person67 - person
	person68 - person
	person69 - person
	person70 - person
	person71 - person
	person72 - person
	person73 - person
	person74 - person
	person75 - person
	person76 - person
	person77 - person
	person78 - person
	person79 - person
	person80 - person
)
(:init
	(drone-at drone1 depot)
	(arm-free-left drone1)
	(arm-free-right drone1)
	(crate-at crate1 depot)
	(crate-at crate2 depot)
	(crate-at crate3 depot)
	(crate-at crate4 depot)
	(crate-at crate5 depot)
	(crate-at crate6 depot)
	(crate-at crate7 depot)
	(crate-at crate8 depot)
	(crate-at crate9 depot)
	(crate-at crate10 depot)
	(crate-at crate11 depot)
	(crate-at crate12 depot)
	(crate-at crate13 depot)
	(crate-at crate14 depot)
	(crate-at crate15 depot)
	(crate-at crate16 depot)
	(crate-at crate17 depot)
	(crate-at crate18 depot)
	(crate-at crate19 depot)
	(crate-at crate20 depot)
	(crate-at crate21 depot)
	(crate-at crate22 depot)
	(crate-at crate23 depot)
	(crate-at crate24 depot)
	(crate-at crate25 depot)
	(crate-at crate26 depot)
	(crate-at crate27 depot)
	(crate-at crate28 depot)
	(crate-at crate29 depot)
	(crate-at crate30 depot)
	(crate-at crate31 depot)
	(crate-at crate32 depot)
	(crate-at crate33 depot)
	(crate-at crate34 depot)
	(crate-at crate35 depot)
	(crate-at crate36 depot)
	(crate-at crate37 depot)
	(crate-at crate38 depot)
	(crate-at crate39 depot)
	(crate-at crate40 depot)
	(crate-at crate41 depot)
	(crate-at crate42 depot)
	(crate-at crate43 depot)
	(crate-at crate44 depot)
	(crate-at crate45 depot)
	(crate-at crate46 depot)
	(crate-at crate47 depot)
	(crate-at crate48 depot)
	(crate-at crate49 depot)
	(crate-at crate50 depot)
	(crate-at crate51 depot)
	(crate-at crate52 depot)
	(crate-at crate53 depot)
	(crate-at crate54 depot)
	(crate-at crate55 depot)
	(crate-at crate56 depot)
	(crate-at crate57 depot)
	(crate-at crate58 depot)
	(crate-at crate59 depot)
	(crate-at crate60 depot)
	(crate-at crate61 depot)
	(crate-at crate62 depot)
	(crate-at crate63 depot)
	(crate-at crate64 depot)
	(crate-at crate65 depot)
	(crate-at crate66 depot)
	(crate-at crate67 depot)
	(crate-at crate68 depot)
	(crate-at crate69 depot)
	(crate-at crate70 depot)
	(crate-at crate71 depot)
	(crate-at crate72 depot)
	(crate-at crate73 depot)
	(crate-at crate74 depot)
	(crate-at crate75 depot)
	(crate-at crate76 depot)
	(crate-at crate77 depot)
	(crate-at crate78 depot)
	(crate-at crate79 depot)
	(crate-at crate80 depot)
	(crate-has crate1 food)
	(crate-has crate2 food)
	(crate-has crate3 medicine)
	(crate-has crate4 medicine)
	(crate-has crate5 medicine)
	(crate-has crate6 medicine)
	(crate-has crate7 medicine)
	(crate-has crate8 medicine)
	(crate-has crate9 medicine)
	(crate-has crate10 medicine)
	(crate-has crate11 medicine)
	(crate-has crate12 medicine)
	(crate-has crate13 medicine)
	(crate-has crate14 medicine)
	(crate-has crate15 medicine)
	(crate-has crate16 medicine)
	(crate-has crate17 medicine)
	(crate-has crate18 medicine)
	(crate-has crate19 medicine)
	(crate-has crate20 medicine)
	(crate-has crate21 medicine)
	(crate-has crate22 medicine)
	(crate-has crate23 medicine)
	(crate-has crate24 medicine)
	(crate-has crate25 medicine)
	(crate-has crate26 medicine)
	(crate-has crate27 medicine)
	(crate-has crate28 medicine)
	(crate-has crate29 medicine)
	(crate-has crate30 medicine)
	(crate-has crate31 medicine)
	(crate-has crate32 medicine)
	(crate-has crate33 medicine)
	(crate-has crate34 medicine)
	(crate-has crate35 medicine)
	(crate-has crate36 medicine)
	(crate-has crate37 medicine)
	(crate-has crate38 medicine)
	(crate-has crate39 medicine)
	(crate-has crate40 medicine)
	(crate-has crate41 medicine)
	(crate-has crate42 medicine)
	(crate-has crate43 medicine)
	(crate-has crate44 medicine)
	(crate-has crate45 medicine)
	(crate-has crate46 medicine)
	(crate-has crate47 medicine)
	(crate-has crate48 medicine)
	(crate-has crate49 medicine)
	(crate-has crate50 medicine)
	(crate-has crate51 medicine)
	(crate-has crate52 medicine)
	(crate-has crate53 medicine)
	(crate-has crate54 medicine)
	(crate-has crate55 medicine)
	(crate-has crate56 medicine)
	(crate-has crate57 medicine)
	(crate-has crate58 medicine)
	(crate-has crate59 medicine)
	(crate-has crate60 medicine)
	(crate-has crate61 medicine)
	(crate-has crate62 medicine)
	(crate-has crate63 medicine)
	(crate-has crate64 medicine)
	(crate-has crate65 medicine)
	(crate-has crate66 medicine)
	(crate-has crate67 medicine)
	(crate-has crate68 medicine)
	(crate-has crate69 medicine)
	(crate-has crate70 medicine)
	(crate-has crate71 medicine)
	(crate-has crate72 medicine)
	(crate-has crate73 medicine)
	(crate-has crate74 medicine)
	(crate-has crate75 medicine)
	(crate-has crate76 medicine)
	(crate-has crate77 medicine)
	(crate-has crate78 medicine)
	(crate-has crate79 medicine)
	(crate-has crate80 medicine)
	(person-at person1 loc60)
	(person-at person2 loc24)
	(person-at person3 loc68)
	(person-at person4 loc74)
	(person-at person5 loc70)
	(person-at person6 loc21)
	(person-at person7 loc16)
	(person-at person8 loc25)
	(person-at person9 loc64)
	(person-at person10 loc16)
	(person-at person11 loc30)
	(person-at person12 loc55)
	(person-at person13 loc3)
	(person-at person14 loc71)
	(person-at person15 loc64)
	(person-at person16 loc63)
	(person-at person17 loc36)
	(person-at person18 loc6)
	(person-at person19 loc8)
	(person-at person20 loc8)
	(person-at person21 loc76)
	(person-at person22 loc44)
	(person-at person23 loc69)
	(person-at person24 loc38)
	(person-at person25 loc4)
	(person-at person26 loc24)
	(person-at person27 loc50)
	(person-at person28 loc66)
	(person-at person29 loc22)
	(person-at person30 loc65)
	(person-at person31 loc52)
	(person-at person32 loc38)
	(person-at person33 loc60)
	(person-at person34 loc74)
	(person-at person35 loc22)
	(person-at person36 loc51)
	(person-at person37 loc77)
	(person-at person38 loc64)
	(person-at person39 loc35)
	(person-at person40 loc32)
	(person-at person41 loc44)
	(person-at person42 loc54)
	(person-at person43 loc77)
	(person-at person44 loc71)
	(person-at person45 loc58)
	(person-at person46 loc65)
	(person-at person47 loc12)
	(person-at person48 loc74)
	(person-at person49 loc51)
	(person-at person50 loc7)
	(person-at person51 loc79)
	(person-at person52 loc54)
	(person-at person53 loc45)
	(person-at person54 loc34)
	(person-at person55 loc73)
	(person-at person56 loc23)
	(person-at person57 loc31)
	(person-at person58 loc28)
	(person-at person59 loc36)
	(person-at person60 loc9)
	(person-at person61 loc64)
	(person-at person62 loc38)
	(person-at person63 loc46)
	(person-at person64 loc4)
	(person-at person65 loc79)
	(person-at person66 loc23)
	(person-at person67 loc58)
	(person-at person68 loc68)
	(person-at person69 loc62)
	(person-at person70 loc16)
	(person-at person71 loc48)
	(person-at person72 loc6)
	(person-at person73 loc38)
	(person-at person74 loc52)
	(person-at person75 loc8)
	(person-at person76 loc33)
	(person-at person77 loc48)
	(person-at person78 loc44)
	(person-at person79 loc16)
	(person-at person80 loc28)
)
(:goal (and

	(drone-at drone1 depot)	(person-has person1 medicine)
	(person-has person2 medicine)
	(person-has person3 medicine)
	(person-has person4 medicine)
	(person-has person5 medicine)
	(person-has person6 medicine)
	(person-has person7 medicine)
	(person-has person8 medicine)
	(person-has person9 food)
	(person-has person9 medicine)
	(person-has person10 medicine)
	(person-has person11 medicine)
	(person-has person12 medicine)
	(person-has person13 medicine)
	(person-has person14 medicine)
	(person-has person15 medicine)
	(person-has person16 food)
	(person-has person16 medicine)
	(person-has person17 medicine)
	(person-has person18 medicine)
	(person-has person19 medicine)
	(person-has person20 medicine)
	(person-has person21 medicine)
	(person-has person22 medicine)
	(person-has person23 medicine)
	(person-has person24 medicine)
	(person-has person26 medicine)
	(person-has person27 medicine)
	(person-has person28 medicine)
	(person-has person29 medicine)
	(person-has person30 medicine)
	(person-has person31 medicine)
	(person-has person32 medicine)
	(person-has person34 medicine)
	(person-has person35 medicine)
	(person-has person36 medicine)
	(person-has person37 medicine)
	(person-has person38 medicine)
	(person-has person39 medicine)
	(person-has person40 medicine)
	(person-has person41 medicine)
	(person-has person42 medicine)
	(person-has person43 medicine)
	(person-has person44 medicine)
	(person-has person45 medicine)
	(person-has person46 medicine)
	(person-has person47 medicine)
	(person-has person48 medicine)
	(person-has person49 medicine)
	(person-has person50 medicine)
	(person-has person51 medicine)
	(person-has person52 medicine)
	(person-has person53 medicine)
	(person-has person54 medicine)
	(person-has person55 medicine)
	(person-has person56 medicine)
	(person-has person57 medicine)
	(person-has person58 medicine)
	(person-has person59 medicine)
	(person-has person60 medicine)
	(person-has person61 medicine)
	(person-has person62 medicine)
	(person-has person63 medicine)
	(person-has person64 medicine)
	(person-has person65 medicine)
	(person-has person66 medicine)
	(person-has person67 medicine)
	(person-has person68 medicine)
	(person-has person69 medicine)
	(person-has person70 medicine)
	(person-has person71 medicine)
	(person-has person72 medicine)
	(person-has person73 medicine)
	(person-has person74 medicine)
	(person-has person75 medicine)
	(person-has person76 medicine)
	(person-has person77 medicine)
	(person-has person78 medicine)
	(person-has person79 medicine)
	(person-has person80 medicine)
	))
)
