(define (problem drone_problem_d1_r0_l50_p50_c50_g50_ct2)
(:domain ubermedics)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	loc36 - location
	loc37 - location
	loc38 - location
	loc39 - location
	loc40 - location
	loc41 - location
	loc42 - location
	loc43 - location
	loc44 - location
	loc45 - location
	loc46 - location
	loc47 - location
	loc48 - location
	loc49 - location
	loc50 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	crate43 - crate
	crate44 - crate
	crate45 - crate
	crate46 - crate
	crate47 - crate
	crate48 - crate
	crate49 - crate
	crate50 - crate
	food - contents
	medicine - contents
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	person34 - person
	person35 - person
	person36 - person
	person37 - person
	person38 - person
	person39 - person
	person40 - person
	person41 - person
	person42 - person
	person43 - person
	person44 - person
	person45 - person
	person46 - person
	person47 - person
	person48 - person
	person49 - person
	person50 - person
)
(:init
	(drone-at drone1 depot)
	(arm-free-left drone1)
	(arm-free-right drone1)
	(crate-at crate1 depot)
	(crate-at crate2 depot)
	(crate-at crate3 depot)
	(crate-at crate4 depot)
	(crate-at crate5 depot)
	(crate-at crate6 depot)
	(crate-at crate7 depot)
	(crate-at crate8 depot)
	(crate-at crate9 depot)
	(crate-at crate10 depot)
	(crate-at crate11 depot)
	(crate-at crate12 depot)
	(crate-at crate13 depot)
	(crate-at crate14 depot)
	(crate-at crate15 depot)
	(crate-at crate16 depot)
	(crate-at crate17 depot)
	(crate-at crate18 depot)
	(crate-at crate19 depot)
	(crate-at crate20 depot)
	(crate-at crate21 depot)
	(crate-at crate22 depot)
	(crate-at crate23 depot)
	(crate-at crate24 depot)
	(crate-at crate25 depot)
	(crate-at crate26 depot)
	(crate-at crate27 depot)
	(crate-at crate28 depot)
	(crate-at crate29 depot)
	(crate-at crate30 depot)
	(crate-at crate31 depot)
	(crate-at crate32 depot)
	(crate-at crate33 depot)
	(crate-at crate34 depot)
	(crate-at crate35 depot)
	(crate-at crate36 depot)
	(crate-at crate37 depot)
	(crate-at crate38 depot)
	(crate-at crate39 depot)
	(crate-at crate40 depot)
	(crate-at crate41 depot)
	(crate-at crate42 depot)
	(crate-at crate43 depot)
	(crate-at crate44 depot)
	(crate-at crate45 depot)
	(crate-at crate46 depot)
	(crate-at crate47 depot)
	(crate-at crate48 depot)
	(crate-at crate49 depot)
	(crate-at crate50 depot)
	(crate-has crate1 food)
	(crate-has crate2 food)
	(crate-has crate3 food)
	(crate-has crate4 food)
	(crate-has crate5 food)
	(crate-has crate6 food)
	(crate-has crate7 food)
	(crate-has crate8 food)
	(crate-has crate9 food)
	(crate-has crate10 food)
	(crate-has crate11 food)
	(crate-has crate12 food)
	(crate-has crate13 food)
	(crate-has crate14 food)
	(crate-has crate15 food)
	(crate-has crate16 food)
	(crate-has crate17 food)
	(crate-has crate18 food)
	(crate-has crate19 food)
	(crate-has crate20 food)
	(crate-has crate21 food)
	(crate-has crate22 food)
	(crate-has crate23 medicine)
	(crate-has crate24 medicine)
	(crate-has crate25 medicine)
	(crate-has crate26 medicine)
	(crate-has crate27 medicine)
	(crate-has crate28 medicine)
	(crate-has crate29 medicine)
	(crate-has crate30 medicine)
	(crate-has crate31 medicine)
	(crate-has crate32 medicine)
	(crate-has crate33 medicine)
	(crate-has crate34 medicine)
	(crate-has crate35 medicine)
	(crate-has crate36 medicine)
	(crate-has crate37 medicine)
	(crate-has crate38 medicine)
	(crate-has crate39 medicine)
	(crate-has crate40 medicine)
	(crate-has crate41 medicine)
	(crate-has crate42 medicine)
	(crate-has crate43 medicine)
	(crate-has crate44 medicine)
	(crate-has crate45 medicine)
	(crate-has crate46 medicine)
	(crate-has crate47 medicine)
	(crate-has crate48 medicine)
	(crate-has crate49 medicine)
	(crate-has crate50 medicine)
	(person-at person1 loc14)
	(person-at person2 loc36)
	(person-at person3 loc28)
	(person-at person4 loc34)
	(person-at person5 loc49)
	(person-at person6 loc20)
	(person-at person7 loc21)
	(person-at person8 loc7)
	(person-at person9 loc47)
	(person-at person10 loc8)
	(person-at person11 loc22)
	(person-at person12 loc42)
	(person-at person13 loc45)
	(person-at person14 loc5)
	(person-at person15 loc32)
	(person-at person16 loc33)
	(person-at person17 loc42)
	(person-at person18 loc18)
	(person-at person19 loc48)
	(person-at person20 loc16)
	(person-at person21 loc48)
	(person-at person22 loc30)
	(person-at person23 loc34)
	(person-at person24 loc8)
	(person-at person25 loc26)
	(person-at person26 loc26)
	(person-at person27 loc50)
	(person-at person28 loc38)
	(person-at person29 loc7)
	(person-at person30 loc47)
	(person-at person31 loc37)
	(person-at person32 loc35)
	(person-at person33 loc48)
	(person-at person34 loc21)
	(person-at person35 loc24)
	(person-at person36 loc10)
	(person-at person37 loc13)
	(person-at person38 loc9)
	(person-at person39 loc16)
	(person-at person40 loc5)
	(person-at person41 loc1)
	(person-at person42 loc48)
	(person-at person43 loc18)
	(person-at person44 loc25)
	(person-at person45 loc15)
	(person-at person46 loc44)
	(person-at person47 loc9)
	(person-at person48 loc29)
	(person-at person49 loc30)
	(person-at person50 loc14)
)
(:goal (and

	(drone-at drone1 depot)	(person-has person1 medicine)
	(person-has person2 food)
	(person-has person3 food)
	(person-has person3 medicine)
	(person-has person4 food)
	(person-has person4 medicine)
	(person-has person6 food)
	(person-has person9 medicine)
	(person-has person11 medicine)
	(person-has person12 food)
	(person-has person12 medicine)
	(person-has person13 food)
	(person-has person13 medicine)
	(person-has person14 medicine)
	(person-has person15 medicine)
	(person-has person16 medicine)
	(person-has person17 food)
	(person-has person17 medicine)
	(person-has person18 food)
	(person-has person19 food)
	(person-has person19 medicine)
	(person-has person21 medicine)
	(person-has person22 food)
	(person-has person22 medicine)
	(person-has person23 food)
	(person-has person23 medicine)
	(person-has person24 medicine)
	(person-has person26 food)
	(person-has person26 medicine)
	(person-has person27 food)
	(person-has person27 medicine)
	(person-has person28 medicine)
	(person-has person29 food)
	(person-has person29 medicine)
	(person-has person30 food)
	(person-has person32 medicine)
	(person-has person33 food)
	(person-has person34 food)
	(person-has person34 medicine)
	(person-has person35 medicine)
	(person-has person37 food)
	(person-has person38 food)
	(person-has person38 medicine)
	(person-has person40 medicine)
	(person-has person41 food)
	(person-has person42 food)
	(person-has person42 medicine)
	(person-has person48 medicine)
	(person-has person49 food)
	(person-has person49 medicine)
	))
)
